#!/usr/bin/perl
use warnings;

#We use the storage routine from Excel data
open (FILEHANDLE,'longcodif.txt');
@exons = <FILEHANDLE>;
close(FILEHANDLE);
chomp(@exons);

foreach $row(@exons){
	@ID = split("\t",$row);	
	foreach $column(@ID){
		push(@TODO,$column);

}}

#We also extract in a new file all the information from the CDS
open (FILE,'>longcodifcoord.txt');
for($i=0;$i<=$#TODO;$i+=5){
	$totallong = $TODO[$i+2]-$TODO[$i+1];
	$intronlong = $TODO[$i+4]-$TODO[$i+3];
	$exonlong = $totallong - $intronlong;
	print FILE  $TODO[$i],"\t",$TODO[$i+1],"\t",$TODO[$i+2],"\t",$totallong,"\t",$TODO[$i+3],"\t",$TODO[$i+4],"\t",$intronlong,"\t",$exonlong,"\n";}
	
