#!/usr/bin/perl
use warnings;

#The routine store all the data from the Exel file and we also store in an array the different species fasta sequences to search the transcripts
@pr = <FILEHANDLE>;
close(FILEHANDLE);
chomp(@pr);

@Fastainputs = ("ailuropoda_melanoleuca_novel.fa","microcebus_murinus_novel.fa","bos_taurus_novel.fa","microtus_ochrogaster_novel.fa","callithrix_jacchus_novel.fa",    "monodelphis_domestica_novel.fa","canis_familiaris_novel.fa","mus_musculus_novel.fa","chinchilla_lanigera_novel.fa","myotis_brandtii_novel.fa","equus_caballus_novel.fa",         "pan_paniscus_novel.fa","felis_catus_novel.fa","panthera_tigris_novel.fa","gorilla_gorilla_novel.fa","pan_troglodytes_novel.fa","heterocephalus_glaber_novel.fa","papio_anubis_novel.fa",
"homo_sapiens_novel.fa","pongo_pygmaeus_novel.fa","ornithorhynchus_anatinus_novel.fa","oryctolagus_cuniculus_novel.fa","ovis_aries_novel.fa","macaca_fascicularis_novel.fa",     "rattus_norvegicus_novel.fa","macaca_mulatta_novel.fa","saimiri_boliviensis_novel.fa","macropus_eugenii_novel.fa","sus_scrofa_novel.fa","tarsius_syrichta_novel.fa","lynx_pardinus_novel.fa ");

foreach $row(@pr){
	@ID = split("\t",$row);	
	foreach $column(@ID){
		push(@TODO,$column);

}}

for($i=0;$i<=$#TODO;$i+=2){
	$protein = $TODO[$i];
	push (@proteins, $protein);
	$transcripts = $TODO[$i+1];
	push (@transcriptslist,$transcripts);}

$j=0;

#foreach protein we make possible saving the transcripts with its protein name, and then we eould do the same for the introns of each protein.
foreach $element(@proteins){
	open(OUT,">$element-transcripts.fa");
	@cuffsep = split(',',$transcriptslist[$j]);
	Get_prot();
	my %hash   = map { $_, 1 } @allseq;
	my @unique = keys %hash;
	for($t=0;$t<=$#unique;$t++){
		print OUT "$unique[$t]\n";}
	undef(@allseq);
	undef(@cuffsep);
	undef($cuff);
	$j=$j+1;
	}

#This subroutine allow us to search the Cufflink data that made hit with the gene and get these sequences in order to make 
#then a blast with the introns of the gene in human.
sub Get_prot
{
foreach $cuffsep(@cuffsep){
	@cuffs = split("'",$cuffsep);
	if ($cuffs[3] =~ /^CUFF/){
		$cuff =	$cuffs[3];}
	elsif ($cuffs[2] =~ /^CUFF/){
		$cuff =	$cuffs[2];}
	elsif ($cuffs[4] =~ /^CUFF/){
		$cuff =	$cuffs[4];}
	else {
		$cuff = "NA";}
	print $cuff,"\n";
	foreach $input(@Fastainputs){
		open(SEQ,"<$input") || die "cannot find $input file!\n";
		$/='>';
		while(<SEQ>)
			{
			if (/$cuff/ and defined($cuff) and $cuff ne "NA")
				{
				$entry=">".$_;
				$l=length($entry);
				$seq_all=substr($entry,0,$l-1);
				push(@allseq,$seq_all)
				}
			}
		close(SEQ);
		$/="\n";
		}}}


	

